//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
namespace dbMantenimiento2Biz
{
	/// <summary>
	/// Main entry point into the database.
	/// 'Get' calls fetch data using the QueryCriteria object.
	/// 'New' calls create new objects/rows.
	/// The CommitAll() function will need to be called at the end.
	/// </summary>
	/// <example>
	/// Example of retrieving a contact and some of it's child rows from the database.
	/// <code>
	/// DataManager dm = new DataManager(Config.Dsn);
	/// dm.QueryCriteria.And(JoinPath.Contact.Teacher.Schedule.Columns.Duration,30,MatchType.GreaterOrEqual);
	/// Contact c = dm.GetContact(FetchPath.Contact.Teacher.All);
	/// </code>
	/// Example of an insert
	/// <code>
	/// DataManager dm = new DataManager(Config.Dsn);
	/// Contact c = dm.NewContact();
	/// dm.CommitAll();
	/// </code>
	/// Example of fetching a collection of rows
	/// <code>
	/// DataManager dm = new DataManager(Config.Dsn);
	/// ContactCollection c = dm.GetContactCollection(FetchPath.Contact.Teacher.All);
	/// </code>
	/// </example>
	public class DataManager : OrmLib.DataManagerBase
	{
		/// <summary>
		/// Constructor for dsn.
		/// </summary>
		public DataManager(string dsn) : base(dsn, dbMantenimiento2Biz.OrmDataSet.NewDataSet()){}

		/// <summary>
		/// Constructor for connections.
		/// </summary>
		public DataManager(System.Data.SqlClient.SqlConnection connection) : base(connection, dbMantenimiento2Biz.OrmDataSet.NewDataSet()){}
		
		/// <summary>
		/// Constructor for transactions.
		/// </summary>
		public DataManager(System.Data.SqlClient.SqlTransaction transaction) : base(transaction, dbMantenimiento2Biz.OrmDataSet.NewDataSet()){}
		
		/// <summary>
		/// Lookup object for static tables
		/// </summary>
		/// <remarks>
		/// This is an internal field and should not be used.
		/// </remarks>
		internal dbMantenimiento2Biz.Lookups lookups;
		
		/// <summary>
		/// Fetches the lookup object
		/// TODO: refresh the lookup object
		/// </summary>
		/// <remarks>
		/// This is an internal method and should not be used.
		/// </remarks>
		/// <returns></returns>
		internal dbMantenimiento2Biz.Lookups GetLookups()
		{
			if (lookups == null)
			{
				lookups = new dbMantenimiento2Biz.Lookups(this.Dsn);
			}
			return lookups;
		}


		/// <summary>
		/// Creates a new aprobacion.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new aprobacion object</returns>
		public dbMantenimiento2Biz.aprobacion Newaprobacion(System.Int32 id)
		{
			System.Data.DataRow dr = DataSet.Tables["aprobacion"].NewRow();
			DataSet.Tables["aprobacion"].Rows.Add( dr );
			dbMantenimiento2Biz.aprobacion _aprobacion = new dbMantenimiento2Biz.aprobacion(this, dr);
			
			_aprobacion.id = id;
						
			return _aprobacion;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.aprobacion based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A aprobacion, or null if not found</returns>
		public dbMantenimiento2Biz.aprobacion  Getaprobacion(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("aprobacion", relations), ds, false);

			System.Data.DataRow aprobacionRow = GetRow(ds, "aprobacion");

			if ( aprobacionRow == null ) return null;
			return new dbMantenimiento2Biz.aprobacion (this,  aprobacionRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.aprobacion from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["aprobacionid"] = _aprobacion.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _aprobacion = dm.GetContactFromDataSet((System.Int32)Session["aprobacionid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A aprobacion, or null if not found</returns>
		public dbMantenimiento2Biz.aprobacion GetaprobacionFromDataSet(System.Int32 id)
		{
			System.Data.DataRow aprobacionRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["aprobacion"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					aprobacionRow = dr;
					break;
				}
			}
			
			if ( aprobacionRow == null) return null;
			return new dbMantenimiento2Biz.aprobacion (this, aprobacionRow);
		}
		/// <summary>
		/// Gets multiple aprobacions based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of aprobacion objects</returns>
		public dbMantenimiento2Biz.aprobacionCollection GetaprobacionCollection()
		{
			return GetaprobacionCollection(FetchPath.aprobacion);
		}
		/// <summary>
		/// Gets multiple aprobacions based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of aprobacion objects</returns>
		public dbMantenimiento2Biz.aprobacionCollection GetaprobacionCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("aprobacion", relations), ds, false);
			
			System.Data.DataRow[] aprobacionList = GetRows(ds,"aprobacion");

			if ( aprobacionList == null ) return null;

			dbMantenimiento2Biz.aprobacionCollection a = new dbMantenimiento2Biz.aprobacionCollection();
			
			foreach ( System.Data.DataRow dr in aprobacionList )
				a.Add(new dbMantenimiento2Biz.aprobacion( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of aprobacion from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all aprobacion loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["aprobacionID"] = _aprobacion.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _aprobacion = dm.GetContactFromDataSet((int)Session["aprobacionID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of aprobacion objects.</returns>
		public dbMantenimiento2Biz.aprobacionCollection GetaprobacionCollectionFromDataSet()
		{
			System.Data.DataRow[] aprobacionList = GetRows(DataSet, "aprobacion");
			dbMantenimiento2Biz.aprobacionCollection a = new dbMantenimiento2Biz.aprobacionCollection();
			
			foreach(System.Data.DataRow dr in aprobacionList )
				a.Add( new dbMantenimiento2Biz.aprobacion(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new componente.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new componente object</returns>
		public dbMantenimiento2Biz.componente Newcomponente(System.String id,
			System.String nombre,
			System.String marca,
			dbMantenimiento2Biz.proveedor parentproveedor)
		{
			System.Data.DataRow dr = DataSet.Tables["componente"].NewRow();
			DataSet.Tables["componente"].Rows.Add( dr );
			dbMantenimiento2Biz.componente _componente = new dbMantenimiento2Biz.componente(this, dr);
			
			_componente.id = id;
			_componente.nombre = nombre;
			_componente.marca = marca;
			_componente.proveedor = parentproveedor;
						
			return _componente;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.componente based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A componente, or null if not found</returns>
		public dbMantenimiento2Biz.componente  Getcomponente(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("componente", relations), ds, false);

			System.Data.DataRow componenteRow = GetRow(ds, "componente");

			if ( componenteRow == null ) return null;
			return new dbMantenimiento2Biz.componente (this,  componenteRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.componente from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["componenteid"] = _componente.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _componente = dm.GetContactFromDataSet((System.String)Session["componenteid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A componente, or null if not found</returns>
		public dbMantenimiento2Biz.componente GetcomponenteFromDataSet(System.String id)
		{
			System.Data.DataRow componenteRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["componente"].Rows)
			{
				if ( ((System.String)dr["id"]).ToString() == id.ToString() ) 
				{
					componenteRow = dr;
					break;
				}
			}
			
			if ( componenteRow == null) return null;
			return new dbMantenimiento2Biz.componente (this, componenteRow);
		}
		/// <summary>
		/// Gets multiple componentes based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of componente objects</returns>
		public dbMantenimiento2Biz.componenteCollection GetcomponenteCollection()
		{
			return GetcomponenteCollection(FetchPath.componente);
		}
		/// <summary>
		/// Gets multiple componentes based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of componente objects</returns>
		public dbMantenimiento2Biz.componenteCollection GetcomponenteCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("componente", relations), ds, false);
			
			System.Data.DataRow[] componenteList = GetRows(ds,"componente");

			if ( componenteList == null ) return null;

			dbMantenimiento2Biz.componenteCollection a = new dbMantenimiento2Biz.componenteCollection();
			
			foreach ( System.Data.DataRow dr in componenteList )
				a.Add(new dbMantenimiento2Biz.componente( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of componente from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all componente loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["componenteID"] = _componente.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _componente = dm.GetContactFromDataSet((int)Session["componenteID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of componente objects.</returns>
		public dbMantenimiento2Biz.componenteCollection GetcomponenteCollectionFromDataSet()
		{
			System.Data.DataRow[] componenteList = GetRows(DataSet, "componente");
			dbMantenimiento2Biz.componenteCollection a = new dbMantenimiento2Biz.componenteCollection();
			
			foreach(System.Data.DataRow dr in componenteList )
				a.Add( new dbMantenimiento2Biz.componente(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new detalle_reparo.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new detalle_reparo object</returns>
		public dbMantenimiento2Biz.detalle_reparo Newdetalle_reparo(System.Int32 id)
		{
			System.Data.DataRow dr = DataSet.Tables["detalle_reparo"].NewRow();
			DataSet.Tables["detalle_reparo"].Rows.Add( dr );
			dbMantenimiento2Biz.detalle_reparo _detalle_reparo = new dbMantenimiento2Biz.detalle_reparo(this, dr);
			
			_detalle_reparo.id = id;
						
			return _detalle_reparo;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.detalle_reparo based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A detalle_reparo, or null if not found</returns>
		public dbMantenimiento2Biz.detalle_reparo  Getdetalle_reparo(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("detalle_reparo", relations), ds, false);

			System.Data.DataRow detalle_reparoRow = GetRow(ds, "detalle_reparo");

			if ( detalle_reparoRow == null ) return null;
			return new dbMantenimiento2Biz.detalle_reparo (this,  detalle_reparoRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.detalle_reparo from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["detalle_reparoid"] = _detalle_reparo.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _detalle_reparo = dm.GetContactFromDataSet((System.Int32)Session["detalle_reparoid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A detalle_reparo, or null if not found</returns>
		public dbMantenimiento2Biz.detalle_reparo Getdetalle_reparoFromDataSet(System.Int32 id)
		{
			System.Data.DataRow detalle_reparoRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["detalle_reparo"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					detalle_reparoRow = dr;
					break;
				}
			}
			
			if ( detalle_reparoRow == null) return null;
			return new dbMantenimiento2Biz.detalle_reparo (this, detalle_reparoRow);
		}
		/// <summary>
		/// Gets multiple detalle_reparos based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of detalle_reparo objects</returns>
		public dbMantenimiento2Biz.detalle_reparoCollection Getdetalle_reparoCollection()
		{
			return Getdetalle_reparoCollection(FetchPath.detalle_reparo);
		}
		/// <summary>
		/// Gets multiple detalle_reparos based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of detalle_reparo objects</returns>
		public dbMantenimiento2Biz.detalle_reparoCollection Getdetalle_reparoCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("detalle_reparo", relations), ds, false);
			
			System.Data.DataRow[] detalle_reparoList = GetRows(ds,"detalle_reparo");

			if ( detalle_reparoList == null ) return null;

			dbMantenimiento2Biz.detalle_reparoCollection a = new dbMantenimiento2Biz.detalle_reparoCollection();
			
			foreach ( System.Data.DataRow dr in detalle_reparoList )
				a.Add(new dbMantenimiento2Biz.detalle_reparo( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of detalle_reparo from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all detalle_reparo loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["detalle_reparoID"] = _detalle_reparo.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _detalle_reparo = dm.GetContactFromDataSet((int)Session["detalle_reparoID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of detalle_reparo objects.</returns>
		public dbMantenimiento2Biz.detalle_reparoCollection Getdetalle_reparoCollectionFromDataSet()
		{
			System.Data.DataRow[] detalle_reparoList = GetRows(DataSet, "detalle_reparo");
			dbMantenimiento2Biz.detalle_reparoCollection a = new dbMantenimiento2Biz.detalle_reparoCollection();
			
			foreach(System.Data.DataRow dr in detalle_reparoList )
				a.Add( new dbMantenimiento2Biz.detalle_reparo(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new empresa.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new empresa object</returns>
		public dbMantenimiento2Biz.empresa Newempresa(System.Int32 id,
			System.String nombre,
			System.String rubro,
			System.String direccion,
			System.String telefono,
			System.Data.SqlTypes.SqlBinary imagen)
		{
			System.Data.DataRow dr = DataSet.Tables["empresa"].NewRow();
			DataSet.Tables["empresa"].Rows.Add( dr );
			dbMantenimiento2Biz.empresa _empresa = new dbMantenimiento2Biz.empresa(this, dr);
			
			_empresa.id = id;
			_empresa.nombre = nombre;
			_empresa.rubro = rubro;
			_empresa.direccion = direccion;
			_empresa.telefono = telefono;
			_empresa.imagen = imagen;
						
			return _empresa;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.empresa based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A empresa, or null if not found</returns>
		public dbMantenimiento2Biz.empresa  Getempresa(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("empresa", relations), ds, false);

			System.Data.DataRow empresaRow = GetRow(ds, "empresa");

			if ( empresaRow == null ) return null;
			return new dbMantenimiento2Biz.empresa (this,  empresaRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.empresa from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["empresaid"] = _empresa.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _empresa = dm.GetContactFromDataSet((System.Int32)Session["empresaid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A empresa, or null if not found</returns>
		public dbMantenimiento2Biz.empresa GetempresaFromDataSet(System.Int32 id)
		{
			System.Data.DataRow empresaRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["empresa"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					empresaRow = dr;
					break;
				}
			}
			
			if ( empresaRow == null) return null;
			return new dbMantenimiento2Biz.empresa (this, empresaRow);
		}
		/// <summary>
		/// Gets multiple empresas based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of empresa objects</returns>
		public dbMantenimiento2Biz.empresaCollection GetempresaCollection()
		{
			return GetempresaCollection(FetchPath.empresa);
		}
		/// <summary>
		/// Gets multiple empresas based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of empresa objects</returns>
		public dbMantenimiento2Biz.empresaCollection GetempresaCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("empresa", relations), ds, false);
			
			System.Data.DataRow[] empresaList = GetRows(ds,"empresa");

			if ( empresaList == null ) return null;

			dbMantenimiento2Biz.empresaCollection a = new dbMantenimiento2Biz.empresaCollection();
			
			foreach ( System.Data.DataRow dr in empresaList )
				a.Add(new dbMantenimiento2Biz.empresa( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of empresa from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all empresa loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["empresaID"] = _empresa.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _empresa = dm.GetContactFromDataSet((int)Session["empresaID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of empresa objects.</returns>
		public dbMantenimiento2Biz.empresaCollection GetempresaCollectionFromDataSet()
		{
			System.Data.DataRow[] empresaList = GetRows(DataSet, "empresa");
			dbMantenimiento2Biz.empresaCollection a = new dbMantenimiento2Biz.empresaCollection();
			
			foreach(System.Data.DataRow dr in empresaList )
				a.Add( new dbMantenimiento2Biz.empresa(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new funcion.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new funcion object</returns>
		public dbMantenimiento2Biz.funcion Newfuncion(System.Int32 id,
			System.String nombre)
		{
			System.Data.DataRow dr = DataSet.Tables["funcion"].NewRow();
			DataSet.Tables["funcion"].Rows.Add( dr );
			dbMantenimiento2Biz.funcion _funcion = new dbMantenimiento2Biz.funcion(this, dr);
			
			_funcion.id = id;
			_funcion.nombre = nombre;
						
			return _funcion;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.funcion based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A funcion, or null if not found</returns>
		public dbMantenimiento2Biz.funcion  Getfuncion(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("funcion", relations), ds, false);

			System.Data.DataRow funcionRow = GetRow(ds, "funcion");

			if ( funcionRow == null ) return null;
			return new dbMantenimiento2Biz.funcion (this,  funcionRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.funcion from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["funcionid"] = _funcion.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _funcion = dm.GetContactFromDataSet((System.Int32)Session["funcionid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A funcion, or null if not found</returns>
		public dbMantenimiento2Biz.funcion GetfuncionFromDataSet(System.Int32 id)
		{
			System.Data.DataRow funcionRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["funcion"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					funcionRow = dr;
					break;
				}
			}
			
			if ( funcionRow == null) return null;
			return new dbMantenimiento2Biz.funcion (this, funcionRow);
		}
		/// <summary>
		/// Gets multiple funcions based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of funcion objects</returns>
		public dbMantenimiento2Biz.funcionCollection GetfuncionCollection()
		{
			return GetfuncionCollection(FetchPath.funcion);
		}
		/// <summary>
		/// Gets multiple funcions based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of funcion objects</returns>
		public dbMantenimiento2Biz.funcionCollection GetfuncionCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("funcion", relations), ds, false);
			
			System.Data.DataRow[] funcionList = GetRows(ds,"funcion");

			if ( funcionList == null ) return null;

			dbMantenimiento2Biz.funcionCollection a = new dbMantenimiento2Biz.funcionCollection();
			
			foreach ( System.Data.DataRow dr in funcionList )
				a.Add(new dbMantenimiento2Biz.funcion( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of funcion from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all funcion loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["funcionID"] = _funcion.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _funcion = dm.GetContactFromDataSet((int)Session["funcionID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of funcion objects.</returns>
		public dbMantenimiento2Biz.funcionCollection GetfuncionCollectionFromDataSet()
		{
			System.Data.DataRow[] funcionList = GetRows(DataSet, "funcion");
			dbMantenimiento2Biz.funcionCollection a = new dbMantenimiento2Biz.funcionCollection();
			
			foreach(System.Data.DataRow dr in funcionList )
				a.Add( new dbMantenimiento2Biz.funcion(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new inventario.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new inventario object</returns>
		public dbMantenimiento2Biz.inventario Newinventario(System.Int32 id)
		{
			System.Data.DataRow dr = DataSet.Tables["inventario"].NewRow();
			DataSet.Tables["inventario"].Rows.Add( dr );
			dbMantenimiento2Biz.inventario _inventario = new dbMantenimiento2Biz.inventario(this, dr);
			
			_inventario.id = id;
						
			return _inventario;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.inventario based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A inventario, or null if not found</returns>
		public dbMantenimiento2Biz.inventario  Getinventario(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("inventario", relations), ds, false);

			System.Data.DataRow inventarioRow = GetRow(ds, "inventario");

			if ( inventarioRow == null ) return null;
			return new dbMantenimiento2Biz.inventario (this,  inventarioRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.inventario from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["inventarioid"] = _inventario.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _inventario = dm.GetContactFromDataSet((System.Int32)Session["inventarioid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A inventario, or null if not found</returns>
		public dbMantenimiento2Biz.inventario GetinventarioFromDataSet(System.Int32 id)
		{
			System.Data.DataRow inventarioRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["inventario"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					inventarioRow = dr;
					break;
				}
			}
			
			if ( inventarioRow == null) return null;
			return new dbMantenimiento2Biz.inventario (this, inventarioRow);
		}
		/// <summary>
		/// Gets multiple inventarios based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of inventario objects</returns>
		public dbMantenimiento2Biz.inventarioCollection GetinventarioCollection()
		{
			return GetinventarioCollection(FetchPath.inventario);
		}
		/// <summary>
		/// Gets multiple inventarios based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of inventario objects</returns>
		public dbMantenimiento2Biz.inventarioCollection GetinventarioCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("inventario", relations), ds, false);
			
			System.Data.DataRow[] inventarioList = GetRows(ds,"inventario");

			if ( inventarioList == null ) return null;

			dbMantenimiento2Biz.inventarioCollection a = new dbMantenimiento2Biz.inventarioCollection();
			
			foreach ( System.Data.DataRow dr in inventarioList )
				a.Add(new dbMantenimiento2Biz.inventario( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of inventario from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all inventario loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["inventarioID"] = _inventario.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _inventario = dm.GetContactFromDataSet((int)Session["inventarioID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of inventario objects.</returns>
		public dbMantenimiento2Biz.inventarioCollection GetinventarioCollectionFromDataSet()
		{
			System.Data.DataRow[] inventarioList = GetRows(DataSet, "inventario");
			dbMantenimiento2Biz.inventarioCollection a = new dbMantenimiento2Biz.inventarioCollection();
			
			foreach(System.Data.DataRow dr in inventarioList )
				a.Add( new dbMantenimiento2Biz.inventario(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new linea_produccion.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new linea_produccion object</returns>
		public dbMantenimiento2Biz.linea_produccion Newlinea_produccion(System.Int32 id,
			System.String nombre,
			System.String descripcion)
		{
			System.Data.DataRow dr = DataSet.Tables["linea_produccion"].NewRow();
			DataSet.Tables["linea_produccion"].Rows.Add( dr );
			dbMantenimiento2Biz.linea_produccion _linea_produccion = new dbMantenimiento2Biz.linea_produccion(this, dr);
			
			_linea_produccion.id = id;
			_linea_produccion.nombre = nombre;
			_linea_produccion.descripcion = descripcion;
						
			return _linea_produccion;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.linea_produccion based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A linea_produccion, or null if not found</returns>
		public dbMantenimiento2Biz.linea_produccion  Getlinea_produccion(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("linea_produccion", relations), ds, false);

			System.Data.DataRow linea_produccionRow = GetRow(ds, "linea_produccion");

			if ( linea_produccionRow == null ) return null;
			return new dbMantenimiento2Biz.linea_produccion (this,  linea_produccionRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.linea_produccion from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["linea_produccionid"] = _linea_produccion.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _linea_produccion = dm.GetContactFromDataSet((System.Int32)Session["linea_produccionid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A linea_produccion, or null if not found</returns>
		public dbMantenimiento2Biz.linea_produccion Getlinea_produccionFromDataSet(System.Int32 id)
		{
			System.Data.DataRow linea_produccionRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["linea_produccion"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					linea_produccionRow = dr;
					break;
				}
			}
			
			if ( linea_produccionRow == null) return null;
			return new dbMantenimiento2Biz.linea_produccion (this, linea_produccionRow);
		}
		/// <summary>
		/// Gets multiple linea_produccions based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of linea_produccion objects</returns>
		public dbMantenimiento2Biz.linea_produccionCollection Getlinea_produccionCollection()
		{
			return Getlinea_produccionCollection(FetchPath.linea_produccion);
		}
		/// <summary>
		/// Gets multiple linea_produccions based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of linea_produccion objects</returns>
		public dbMantenimiento2Biz.linea_produccionCollection Getlinea_produccionCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("linea_produccion", relations), ds, false);
			
			System.Data.DataRow[] linea_produccionList = GetRows(ds,"linea_produccion");

			if ( linea_produccionList == null ) return null;

			dbMantenimiento2Biz.linea_produccionCollection a = new dbMantenimiento2Biz.linea_produccionCollection();
			
			foreach ( System.Data.DataRow dr in linea_produccionList )
				a.Add(new dbMantenimiento2Biz.linea_produccion( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of linea_produccion from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all linea_produccion loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["linea_produccionID"] = _linea_produccion.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _linea_produccion = dm.GetContactFromDataSet((int)Session["linea_produccionID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of linea_produccion objects.</returns>
		public dbMantenimiento2Biz.linea_produccionCollection Getlinea_produccionCollectionFromDataSet()
		{
			System.Data.DataRow[] linea_produccionList = GetRows(DataSet, "linea_produccion");
			dbMantenimiento2Biz.linea_produccionCollection a = new dbMantenimiento2Biz.linea_produccionCollection();
			
			foreach(System.Data.DataRow dr in linea_produccionList )
				a.Add( new dbMantenimiento2Biz.linea_produccion(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new maquina.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new maquina object</returns>
		public dbMantenimiento2Biz.maquina Newmaquina(System.String id,
			System.String nombre,
			System.String marca,
			System.Data.SqlTypes.SqlInt32 anho,
			System.String industria,
			System.String funcion,
			System.String caracteristicas,
			System.Data.SqlTypes.SqlInt32 idlinea,
			System.String estado)
		{
			System.Data.DataRow dr = DataSet.Tables["maquina"].NewRow();
			DataSet.Tables["maquina"].Rows.Add( dr );
			dbMantenimiento2Biz.maquina _maquina = new dbMantenimiento2Biz.maquina(this, dr);
			
			_maquina.id = id;
			_maquina.nombre = nombre;
			_maquina.marca = marca;
			_maquina.anho = anho;
			_maquina.industria = industria;
			_maquina.funcion = funcion;
			_maquina.caracteristicas = caracteristicas;
			_maquina.idlinea = idlinea;
			_maquina.estado = estado;
						
			return _maquina;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.maquina based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A maquina, or null if not found</returns>
		public dbMantenimiento2Biz.maquina  Getmaquina(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("maquina", relations), ds, false);

			System.Data.DataRow maquinaRow = GetRow(ds, "maquina");

			if ( maquinaRow == null ) return null;
			return new dbMantenimiento2Biz.maquina (this,  maquinaRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.maquina from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["maquinaid"] = _maquina.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _maquina = dm.GetContactFromDataSet((System.String)Session["maquinaid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A maquina, or null if not found</returns>
		public dbMantenimiento2Biz.maquina GetmaquinaFromDataSet(System.String id)
		{
			System.Data.DataRow maquinaRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["maquina"].Rows)
			{
				if ( ((System.String)dr["id"]).ToString() == id.ToString() ) 
				{
					maquinaRow = dr;
					break;
				}
			}
			
			if ( maquinaRow == null) return null;
			return new dbMantenimiento2Biz.maquina (this, maquinaRow);
		}
		/// <summary>
		/// Gets multiple maquinas based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of maquina objects</returns>
		public dbMantenimiento2Biz.maquinaCollection GetmaquinaCollection()
		{
			return GetmaquinaCollection(FetchPath.maquina);
		}
		/// <summary>
		/// Gets multiple maquinas based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of maquina objects</returns>
		public dbMantenimiento2Biz.maquinaCollection GetmaquinaCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("maquina", relations), ds, false);
			
			System.Data.DataRow[] maquinaList = GetRows(ds,"maquina");

			if ( maquinaList == null ) return null;

			dbMantenimiento2Biz.maquinaCollection a = new dbMantenimiento2Biz.maquinaCollection();
			
			foreach ( System.Data.DataRow dr in maquinaList )
				a.Add(new dbMantenimiento2Biz.maquina( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of maquina from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all maquina loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["maquinaID"] = _maquina.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _maquina = dm.GetContactFromDataSet((int)Session["maquinaID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of maquina objects.</returns>
		public dbMantenimiento2Biz.maquinaCollection GetmaquinaCollectionFromDataSet()
		{
			System.Data.DataRow[] maquinaList = GetRows(DataSet, "maquina");
			dbMantenimiento2Biz.maquinaCollection a = new dbMantenimiento2Biz.maquinaCollection();
			
			foreach(System.Data.DataRow dr in maquinaList )
				a.Add( new dbMantenimiento2Biz.maquina(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new material_herramienta.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new material_herramienta object</returns>
		public dbMantenimiento2Biz.material_herramienta Newmaterial_herramienta(System.Int32 id,
			dbMantenimiento2Biz.proveedor parentproveedor)
		{
			System.Data.DataRow dr = DataSet.Tables["material_herramienta"].NewRow();
			DataSet.Tables["material_herramienta"].Rows.Add( dr );
			dbMantenimiento2Biz.material_herramienta _material_herramienta = new dbMantenimiento2Biz.material_herramienta(this, dr);
			
			_material_herramienta.id = id;
			_material_herramienta.proveedor = parentproveedor;
						
			return _material_herramienta;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.material_herramienta based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A material_herramienta, or null if not found</returns>
		public dbMantenimiento2Biz.material_herramienta  Getmaterial_herramienta(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("material_herramienta", relations), ds, false);

			System.Data.DataRow material_herramientaRow = GetRow(ds, "material_herramienta");

			if ( material_herramientaRow == null ) return null;
			return new dbMantenimiento2Biz.material_herramienta (this,  material_herramientaRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.material_herramienta from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["material_herramientaid"] = _material_herramienta.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _material_herramienta = dm.GetContactFromDataSet((System.Int32)Session["material_herramientaid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A material_herramienta, or null if not found</returns>
		public dbMantenimiento2Biz.material_herramienta Getmaterial_herramientaFromDataSet(System.Int32 id)
		{
			System.Data.DataRow material_herramientaRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["material_herramienta"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					material_herramientaRow = dr;
					break;
				}
			}
			
			if ( material_herramientaRow == null) return null;
			return new dbMantenimiento2Biz.material_herramienta (this, material_herramientaRow);
		}
		/// <summary>
		/// Gets multiple material_herramientas based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of material_herramienta objects</returns>
		public dbMantenimiento2Biz.material_herramientaCollection Getmaterial_herramientaCollection()
		{
			return Getmaterial_herramientaCollection(FetchPath.material_herramienta);
		}
		/// <summary>
		/// Gets multiple material_herramientas based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of material_herramienta objects</returns>
		public dbMantenimiento2Biz.material_herramientaCollection Getmaterial_herramientaCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("material_herramienta", relations), ds, false);
			
			System.Data.DataRow[] material_herramientaList = GetRows(ds,"material_herramienta");

			if ( material_herramientaList == null ) return null;

			dbMantenimiento2Biz.material_herramientaCollection a = new dbMantenimiento2Biz.material_herramientaCollection();
			
			foreach ( System.Data.DataRow dr in material_herramientaList )
				a.Add(new dbMantenimiento2Biz.material_herramienta( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of material_herramienta from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all material_herramienta loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["material_herramientaID"] = _material_herramienta.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _material_herramienta = dm.GetContactFromDataSet((int)Session["material_herramientaID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of material_herramienta objects.</returns>
		public dbMantenimiento2Biz.material_herramientaCollection Getmaterial_herramientaCollectionFromDataSet()
		{
			System.Data.DataRow[] material_herramientaList = GetRows(DataSet, "material_herramienta");
			dbMantenimiento2Biz.material_herramientaCollection a = new dbMantenimiento2Biz.material_herramientaCollection();
			
			foreach(System.Data.DataRow dr in material_herramientaList )
				a.Add( new dbMantenimiento2Biz.material_herramienta(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new materialusado.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new materialusado object</returns>
		public dbMantenimiento2Biz.materialusado Newmaterialusado(System.Int32 id)
		{
			System.Data.DataRow dr = DataSet.Tables["materialusado"].NewRow();
			DataSet.Tables["materialusado"].Rows.Add( dr );
			dbMantenimiento2Biz.materialusado _materialusado = new dbMantenimiento2Biz.materialusado(this, dr);
			
			_materialusado.id = id;
						
			return _materialusado;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.materialusado based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A materialusado, or null if not found</returns>
		public dbMantenimiento2Biz.materialusado  Getmaterialusado(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("materialusado", relations), ds, false);

			System.Data.DataRow materialusadoRow = GetRow(ds, "materialusado");

			if ( materialusadoRow == null ) return null;
			return new dbMantenimiento2Biz.materialusado (this,  materialusadoRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.materialusado from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["materialusadoid"] = _materialusado.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _materialusado = dm.GetContactFromDataSet((System.Int32)Session["materialusadoid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A materialusado, or null if not found</returns>
		public dbMantenimiento2Biz.materialusado GetmaterialusadoFromDataSet(System.Int32 id)
		{
			System.Data.DataRow materialusadoRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["materialusado"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					materialusadoRow = dr;
					break;
				}
			}
			
			if ( materialusadoRow == null) return null;
			return new dbMantenimiento2Biz.materialusado (this, materialusadoRow);
		}
		/// <summary>
		/// Gets multiple materialusados based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of materialusado objects</returns>
		public dbMantenimiento2Biz.materialusadoCollection GetmaterialusadoCollection()
		{
			return GetmaterialusadoCollection(FetchPath.materialusado);
		}
		/// <summary>
		/// Gets multiple materialusados based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of materialusado objects</returns>
		public dbMantenimiento2Biz.materialusadoCollection GetmaterialusadoCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("materialusado", relations), ds, false);
			
			System.Data.DataRow[] materialusadoList = GetRows(ds,"materialusado");

			if ( materialusadoList == null ) return null;

			dbMantenimiento2Biz.materialusadoCollection a = new dbMantenimiento2Biz.materialusadoCollection();
			
			foreach ( System.Data.DataRow dr in materialusadoList )
				a.Add(new dbMantenimiento2Biz.materialusado( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of materialusado from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all materialusado loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["materialusadoID"] = _materialusado.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _materialusado = dm.GetContactFromDataSet((int)Session["materialusadoID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of materialusado objects.</returns>
		public dbMantenimiento2Biz.materialusadoCollection GetmaterialusadoCollectionFromDataSet()
		{
			System.Data.DataRow[] materialusadoList = GetRows(DataSet, "materialusado");
			dbMantenimiento2Biz.materialusadoCollection a = new dbMantenimiento2Biz.materialusadoCollection();
			
			foreach(System.Data.DataRow dr in materialusadoList )
				a.Add( new dbMantenimiento2Biz.materialusado(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new privilegio.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new privilegio object</returns>
		public dbMantenimiento2Biz.privilegio Newprivilegio(System.Int32 id,
			dbMantenimiento2Biz.funcion parentfuncion,
			dbMantenimiento2Biz.rol parentrol)
		{
			System.Data.DataRow dr = DataSet.Tables["privilegio"].NewRow();
			DataSet.Tables["privilegio"].Rows.Add( dr );
			dbMantenimiento2Biz.privilegio _privilegio = new dbMantenimiento2Biz.privilegio(this, dr);
			
			_privilegio.id = id;
			_privilegio.funcion = parentfuncion;
			_privilegio.rol = parentrol;
						
			return _privilegio;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.privilegio based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A privilegio, or null if not found</returns>
		public dbMantenimiento2Biz.privilegio  Getprivilegio(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("privilegio", relations), ds, false);

			System.Data.DataRow privilegioRow = GetRow(ds, "privilegio");

			if ( privilegioRow == null ) return null;
			return new dbMantenimiento2Biz.privilegio (this,  privilegioRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.privilegio from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["privilegioid"] = _privilegio.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _privilegio = dm.GetContactFromDataSet((System.Int32)Session["privilegioid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A privilegio, or null if not found</returns>
		public dbMantenimiento2Biz.privilegio GetprivilegioFromDataSet(System.Int32 id)
		{
			System.Data.DataRow privilegioRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["privilegio"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					privilegioRow = dr;
					break;
				}
			}
			
			if ( privilegioRow == null) return null;
			return new dbMantenimiento2Biz.privilegio (this, privilegioRow);
		}
		/// <summary>
		/// Gets multiple privilegios based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of privilegio objects</returns>
		public dbMantenimiento2Biz.privilegioCollection GetprivilegioCollection()
		{
			return GetprivilegioCollection(FetchPath.privilegio);
		}
		/// <summary>
		/// Gets multiple privilegios based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of privilegio objects</returns>
		public dbMantenimiento2Biz.privilegioCollection GetprivilegioCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("privilegio", relations), ds, false);
			
			System.Data.DataRow[] privilegioList = GetRows(ds,"privilegio");

			if ( privilegioList == null ) return null;

			dbMantenimiento2Biz.privilegioCollection a = new dbMantenimiento2Biz.privilegioCollection();
			
			foreach ( System.Data.DataRow dr in privilegioList )
				a.Add(new dbMantenimiento2Biz.privilegio( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of privilegio from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all privilegio loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["privilegioID"] = _privilegio.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _privilegio = dm.GetContactFromDataSet((int)Session["privilegioID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of privilegio objects.</returns>
		public dbMantenimiento2Biz.privilegioCollection GetprivilegioCollectionFromDataSet()
		{
			System.Data.DataRow[] privilegioList = GetRows(DataSet, "privilegio");
			dbMantenimiento2Biz.privilegioCollection a = new dbMantenimiento2Biz.privilegioCollection();
			
			foreach(System.Data.DataRow dr in privilegioList )
				a.Add( new dbMantenimiento2Biz.privilegio(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new problema.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new problema object</returns>
		public dbMantenimiento2Biz.problema Newproblema(System.Int32 id)
		{
			System.Data.DataRow dr = DataSet.Tables["problema"].NewRow();
			DataSet.Tables["problema"].Rows.Add( dr );
			dbMantenimiento2Biz.problema _problema = new dbMantenimiento2Biz.problema(this, dr);
			
			_problema.id = id;
						
			return _problema;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.problema based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A problema, or null if not found</returns>
		public dbMantenimiento2Biz.problema  Getproblema(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("problema", relations), ds, false);

			System.Data.DataRow problemaRow = GetRow(ds, "problema");

			if ( problemaRow == null ) return null;
			return new dbMantenimiento2Biz.problema (this,  problemaRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.problema from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["problemaid"] = _problema.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _problema = dm.GetContactFromDataSet((System.Int32)Session["problemaid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A problema, or null if not found</returns>
		public dbMantenimiento2Biz.problema GetproblemaFromDataSet(System.Int32 id)
		{
			System.Data.DataRow problemaRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["problema"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					problemaRow = dr;
					break;
				}
			}
			
			if ( problemaRow == null) return null;
			return new dbMantenimiento2Biz.problema (this, problemaRow);
		}
		/// <summary>
		/// Gets multiple problemas based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of problema objects</returns>
		public dbMantenimiento2Biz.problemaCollection GetproblemaCollection()
		{
			return GetproblemaCollection(FetchPath.problema);
		}
		/// <summary>
		/// Gets multiple problemas based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of problema objects</returns>
		public dbMantenimiento2Biz.problemaCollection GetproblemaCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("problema", relations), ds, false);
			
			System.Data.DataRow[] problemaList = GetRows(ds,"problema");

			if ( problemaList == null ) return null;

			dbMantenimiento2Biz.problemaCollection a = new dbMantenimiento2Biz.problemaCollection();
			
			foreach ( System.Data.DataRow dr in problemaList )
				a.Add(new dbMantenimiento2Biz.problema( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of problema from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all problema loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["problemaID"] = _problema.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _problema = dm.GetContactFromDataSet((int)Session["problemaID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of problema objects.</returns>
		public dbMantenimiento2Biz.problemaCollection GetproblemaCollectionFromDataSet()
		{
			System.Data.DataRow[] problemaList = GetRows(DataSet, "problema");
			dbMantenimiento2Biz.problemaCollection a = new dbMantenimiento2Biz.problemaCollection();
			
			foreach(System.Data.DataRow dr in problemaList )
				a.Add( new dbMantenimiento2Biz.problema(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new proveedor.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new proveedor object</returns>
		public dbMantenimiento2Biz.proveedor Newproveedor(System.Int32 id,
			System.String empresa,
			System.String contacto,
			System.String direccion,
			System.String telefono)
		{
			System.Data.DataRow dr = DataSet.Tables["proveedor"].NewRow();
			DataSet.Tables["proveedor"].Rows.Add( dr );
			dbMantenimiento2Biz.proveedor _proveedor = new dbMantenimiento2Biz.proveedor(this, dr);
			
			_proveedor.id = id;
			_proveedor.empresa = empresa;
			_proveedor.contacto = contacto;
			_proveedor.direccion = direccion;
			_proveedor.telefono = telefono;
						
			return _proveedor;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.proveedor based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A proveedor, or null if not found</returns>
		public dbMantenimiento2Biz.proveedor  Getproveedor(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("proveedor", relations), ds, false);

			System.Data.DataRow proveedorRow = GetRow(ds, "proveedor");

			if ( proveedorRow == null ) return null;
			return new dbMantenimiento2Biz.proveedor (this,  proveedorRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.proveedor from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["proveedorid"] = _proveedor.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _proveedor = dm.GetContactFromDataSet((System.Int32)Session["proveedorid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A proveedor, or null if not found</returns>
		public dbMantenimiento2Biz.proveedor GetproveedorFromDataSet(System.Int32 id)
		{
			System.Data.DataRow proveedorRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["proveedor"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					proveedorRow = dr;
					break;
				}
			}
			
			if ( proveedorRow == null) return null;
			return new dbMantenimiento2Biz.proveedor (this, proveedorRow);
		}
		/// <summary>
		/// Gets multiple proveedors based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of proveedor objects</returns>
		public dbMantenimiento2Biz.proveedorCollection GetproveedorCollection()
		{
			return GetproveedorCollection(FetchPath.proveedor);
		}
		/// <summary>
		/// Gets multiple proveedors based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of proveedor objects</returns>
		public dbMantenimiento2Biz.proveedorCollection GetproveedorCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("proveedor", relations), ds, false);
			
			System.Data.DataRow[] proveedorList = GetRows(ds,"proveedor");

			if ( proveedorList == null ) return null;

			dbMantenimiento2Biz.proveedorCollection a = new dbMantenimiento2Biz.proveedorCollection();
			
			foreach ( System.Data.DataRow dr in proveedorList )
				a.Add(new dbMantenimiento2Biz.proveedor( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of proveedor from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all proveedor loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["proveedorID"] = _proveedor.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _proveedor = dm.GetContactFromDataSet((int)Session["proveedorID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of proveedor objects.</returns>
		public dbMantenimiento2Biz.proveedorCollection GetproveedorCollectionFromDataSet()
		{
			System.Data.DataRow[] proveedorList = GetRows(DataSet, "proveedor");
			dbMantenimiento2Biz.proveedorCollection a = new dbMantenimiento2Biz.proveedorCollection();
			
			foreach(System.Data.DataRow dr in proveedorList )
				a.Add( new dbMantenimiento2Biz.proveedor(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new recomendacion.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new recomendacion object</returns>
		public dbMantenimiento2Biz.recomendacion Newrecomendacion(System.Int32 id,
			System.String Propertyrecomendacion,
			dbMantenimiento2Biz.maquina parentmaquina)
		{
			System.Data.DataRow dr = DataSet.Tables["recomendacion"].NewRow();
			DataSet.Tables["recomendacion"].Rows.Add( dr );
			dbMantenimiento2Biz.recomendacion _recomendacion = new dbMantenimiento2Biz.recomendacion(this, dr);
			
			_recomendacion.id = id;
			_recomendacion.Propertyrecomendacion = Propertyrecomendacion;
			_recomendacion.maquina = parentmaquina;
						
			return _recomendacion;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.recomendacion based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A recomendacion, or null if not found</returns>
		public dbMantenimiento2Biz.recomendacion  Getrecomendacion(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("recomendacion", relations), ds, false);

			System.Data.DataRow recomendacionRow = GetRow(ds, "recomendacion");

			if ( recomendacionRow == null ) return null;
			return new dbMantenimiento2Biz.recomendacion (this,  recomendacionRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.recomendacion from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["recomendacionid"] = _recomendacion.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _recomendacion = dm.GetContactFromDataSet((System.Int32)Session["recomendacionid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A recomendacion, or null if not found</returns>
		public dbMantenimiento2Biz.recomendacion GetrecomendacionFromDataSet(System.Int32 id)
		{
			System.Data.DataRow recomendacionRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["recomendacion"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					recomendacionRow = dr;
					break;
				}
			}
			
			if ( recomendacionRow == null) return null;
			return new dbMantenimiento2Biz.recomendacion (this, recomendacionRow);
		}
		/// <summary>
		/// Gets multiple recomendacions based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of recomendacion objects</returns>
		public dbMantenimiento2Biz.recomendacionCollection GetrecomendacionCollection()
		{
			return GetrecomendacionCollection(FetchPath.recomendacion);
		}
		/// <summary>
		/// Gets multiple recomendacions based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of recomendacion objects</returns>
		public dbMantenimiento2Biz.recomendacionCollection GetrecomendacionCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("recomendacion", relations), ds, false);
			
			System.Data.DataRow[] recomendacionList = GetRows(ds,"recomendacion");

			if ( recomendacionList == null ) return null;

			dbMantenimiento2Biz.recomendacionCollection a = new dbMantenimiento2Biz.recomendacionCollection();
			
			foreach ( System.Data.DataRow dr in recomendacionList )
				a.Add(new dbMantenimiento2Biz.recomendacion( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of recomendacion from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all recomendacion loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["recomendacionID"] = _recomendacion.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _recomendacion = dm.GetContactFromDataSet((int)Session["recomendacionID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of recomendacion objects.</returns>
		public dbMantenimiento2Biz.recomendacionCollection GetrecomendacionCollectionFromDataSet()
		{
			System.Data.DataRow[] recomendacionList = GetRows(DataSet, "recomendacion");
			dbMantenimiento2Biz.recomendacionCollection a = new dbMantenimiento2Biz.recomendacionCollection();
			
			foreach(System.Data.DataRow dr in recomendacionList )
				a.Add( new dbMantenimiento2Biz.recomendacion(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new rol.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new rol object</returns>
		public dbMantenimiento2Biz.rol Newrol(System.Int32 id,
			System.String nombre)
		{
			System.Data.DataRow dr = DataSet.Tables["rol"].NewRow();
			DataSet.Tables["rol"].Rows.Add( dr );
			dbMantenimiento2Biz.rol _rol = new dbMantenimiento2Biz.rol(this, dr);
			
			_rol.id = id;
			_rol.nombre = nombre;
						
			return _rol;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.rol based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A rol, or null if not found</returns>
		public dbMantenimiento2Biz.rol  Getrol(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("rol", relations), ds, false);

			System.Data.DataRow rolRow = GetRow(ds, "rol");

			if ( rolRow == null ) return null;
			return new dbMantenimiento2Biz.rol (this,  rolRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.rol from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["rolid"] = _rol.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _rol = dm.GetContactFromDataSet((System.Int32)Session["rolid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A rol, or null if not found</returns>
		public dbMantenimiento2Biz.rol GetrolFromDataSet(System.Int32 id)
		{
			System.Data.DataRow rolRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["rol"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					rolRow = dr;
					break;
				}
			}
			
			if ( rolRow == null) return null;
			return new dbMantenimiento2Biz.rol (this, rolRow);
		}
		/// <summary>
		/// Gets multiple rols based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of rol objects</returns>
		public dbMantenimiento2Biz.rolCollection GetrolCollection()
		{
			return GetrolCollection(FetchPath.rol);
		}
		/// <summary>
		/// Gets multiple rols based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of rol objects</returns>
		public dbMantenimiento2Biz.rolCollection GetrolCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("rol", relations), ds, false);
			
			System.Data.DataRow[] rolList = GetRows(ds,"rol");

			if ( rolList == null ) return null;

			dbMantenimiento2Biz.rolCollection a = new dbMantenimiento2Biz.rolCollection();
			
			foreach ( System.Data.DataRow dr in rolList )
				a.Add(new dbMantenimiento2Biz.rol( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of rol from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all rol loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["rolID"] = _rol.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _rol = dm.GetContactFromDataSet((int)Session["rolID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of rol objects.</returns>
		public dbMantenimiento2Biz.rolCollection GetrolCollectionFromDataSet()
		{
			System.Data.DataRow[] rolList = GetRows(DataSet, "rol");
			dbMantenimiento2Biz.rolCollection a = new dbMantenimiento2Biz.rolCollection();
			
			foreach(System.Data.DataRow dr in rolList )
				a.Add( new dbMantenimiento2Biz.rol(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new solicitud.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new solicitud object</returns>
		public dbMantenimiento2Biz.solicitud Newsolicitud(System.Int32 id)
		{
			System.Data.DataRow dr = DataSet.Tables["solicitud"].NewRow();
			DataSet.Tables["solicitud"].Rows.Add( dr );
			dbMantenimiento2Biz.solicitud _solicitud = new dbMantenimiento2Biz.solicitud(this, dr);
			
			_solicitud.id = id;
						
			return _solicitud;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.solicitud based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A solicitud, or null if not found</returns>
		public dbMantenimiento2Biz.solicitud  Getsolicitud(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("solicitud", relations), ds, false);

			System.Data.DataRow solicitudRow = GetRow(ds, "solicitud");

			if ( solicitudRow == null ) return null;
			return new dbMantenimiento2Biz.solicitud (this,  solicitudRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.solicitud from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["solicitudid"] = _solicitud.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _solicitud = dm.GetContactFromDataSet((System.Int32)Session["solicitudid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A solicitud, or null if not found</returns>
		public dbMantenimiento2Biz.solicitud GetsolicitudFromDataSet(System.Int32 id)
		{
			System.Data.DataRow solicitudRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["solicitud"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					solicitudRow = dr;
					break;
				}
			}
			
			if ( solicitudRow == null) return null;
			return new dbMantenimiento2Biz.solicitud (this, solicitudRow);
		}
		/// <summary>
		/// Gets multiple solicituds based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of solicitud objects</returns>
		public dbMantenimiento2Biz.solicitudCollection GetsolicitudCollection()
		{
			return GetsolicitudCollection(FetchPath.solicitud);
		}
		/// <summary>
		/// Gets multiple solicituds based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of solicitud objects</returns>
		public dbMantenimiento2Biz.solicitudCollection GetsolicitudCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("solicitud", relations), ds, false);
			
			System.Data.DataRow[] solicitudList = GetRows(ds,"solicitud");

			if ( solicitudList == null ) return null;

			dbMantenimiento2Biz.solicitudCollection a = new dbMantenimiento2Biz.solicitudCollection();
			
			foreach ( System.Data.DataRow dr in solicitudList )
				a.Add(new dbMantenimiento2Biz.solicitud( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of solicitud from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all solicitud loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["solicitudID"] = _solicitud.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _solicitud = dm.GetContactFromDataSet((int)Session["solicitudID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of solicitud objects.</returns>
		public dbMantenimiento2Biz.solicitudCollection GetsolicitudCollectionFromDataSet()
		{
			System.Data.DataRow[] solicitudList = GetRows(DataSet, "solicitud");
			dbMantenimiento2Biz.solicitudCollection a = new dbMantenimiento2Biz.solicitudCollection();
			
			foreach(System.Data.DataRow dr in solicitudList )
				a.Add( new dbMantenimiento2Biz.solicitud(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}

		/// <summary>
		/// Creates a new Usuario.
		/// </summary>
		/// <remarks>
		/// <see cref="OrmLib.DataManagerBase.CommitAll"/> to have this written to the database.
		/// </remarks>
		/// <returns>A new Usuario object</returns>
		public dbMantenimiento2Biz.Usuario NewUsuario(System.Int32 id,
			System.String usuario,
			System.String password,
			dbMantenimiento2Biz.rol parentrol)
		{
			System.Data.DataRow dr = DataSet.Tables["Usuario"].NewRow();
			DataSet.Tables["Usuario"].Rows.Add( dr );
			dbMantenimiento2Biz.Usuario _Usuario = new dbMantenimiento2Biz.Usuario(this, dr);
			
			_Usuario.id = id;
			_Usuario.usuario = usuario;
			_Usuario.password = password;
			_Usuario.rol = parentrol;
						
			return _Usuario;
		}

		/// <summary>
		/// Gets a dbMantenimiento2Biz.Usuario based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A Usuario, or null if not found</returns>
		public dbMantenimiento2Biz.Usuario  GetUsuario(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet( CreateSql("Usuario", relations), ds, false);

			System.Data.DataRow UsuarioRow = GetRow(ds, "Usuario");

			if ( UsuarioRow == null ) return null;
			return new dbMantenimiento2Biz.Usuario (this,  UsuarioRow);
		}		
		
		/// <summary>
		/// Gets a dbMantenimiento2Biz.Usuario from the already loaded records in this DataManager, by primary key.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["Usuarioid"] = _Usuario.id;
		/// 
		/// /* second web page - need to get currend contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _Usuario = dm.GetContactFromDataSet((System.Int32)Session["Usuarioid"]);
		/// </code>
		/// </example>
		/// <param name="id">Primary key of the data row to retrieve.</param>
		/// <returns>A Usuario, or null if not found</returns>
		public dbMantenimiento2Biz.Usuario GetUsuarioFromDataSet(System.Int32 id)
		{
			System.Data.DataRow UsuarioRow = null;
			
			foreach(System.Data.DataRow dr in DataSet.Tables["Usuario"].Rows)
			{
				if ( ((System.Int32)dr["id"]).ToString() == id.ToString() ) 
				{
					UsuarioRow = dr;
					break;
				}
			}
			
			if ( UsuarioRow == null) return null;
			return new dbMantenimiento2Biz.Usuario (this, UsuarioRow);
		}
		/// <summary>
		/// Gets multiple Usuarios based on the criteria specified by QueryCriteria.And(..).
		/// </summary>
		/// <returns>A collection of Usuario objects</returns>
		public dbMantenimiento2Biz.UsuarioCollection GetUsuarioCollection()
		{
			return GetUsuarioCollection(FetchPath.Usuario);
		}
		/// <summary>
		/// Gets multiple Usuarios based on the criteria specified by AddCriteria(..).
		/// </summary>
		/// <param name="relations">Specify which related tables should be fetched during this query</param>
		/// <returns>A collection of Usuario objects</returns>
		public dbMantenimiento2Biz.UsuarioCollection GetUsuarioCollection(params OrmLib.DataManagerBase.FetchPathRelation[] relations)
		{
			System.Data.DataSet ds = OrmDataSet.NewDataSet();
			FillDataSet(CreateSql("Usuario", relations), ds, false);
			
			System.Data.DataRow[] UsuarioList = GetRows(ds,"Usuario");

			if ( UsuarioList == null ) return null;

			dbMantenimiento2Biz.UsuarioCollection a = new dbMantenimiento2Biz.UsuarioCollection();
			
			foreach ( System.Data.DataRow dr in UsuarioList )
				a.Add(new dbMantenimiento2Biz.Usuario( this, dr ));
			
			// must be added afterwards
			a.DataManager = this;
			
			return a;
		}
		
		/// <summary>
		/// Gets a collection of Usuario from the already loaded records in this DataManager instance.
		/// </summary>
		/// <remarks>
		/// This method is made available for when the dataset has been serialized 
		/// from session state or disk. This method will return all Usuario loaded.
		/// </remarks>
		/// <example>
		/// This example shows a reason to use this method.
		/// <code>
		/// /* first web page - save dataset and primary keys */
		/// Session["DataSet"] = dm.DataSet;
		/// Session["UsuarioID"] = _Usuario.ID;
		/// 
		/// /* second web page - need to get current contact */
		/// DataManager dm = new DataManager(Config.Dsn);
		/// dm.DataSet = (DataSet)Session["DataSet"];
		/// _Usuario = dm.GetContactFromDataSet((int)Session["UsuarioID"]);
		/// </code>
		/// </example>
		/// <returns>A collection of Usuario objects.</returns>
		public dbMantenimiento2Biz.UsuarioCollection GetUsuarioCollectionFromDataSet()
		{
			System.Data.DataRow[] UsuarioList = GetRows(DataSet, "Usuario");
			dbMantenimiento2Biz.UsuarioCollection a = new dbMantenimiento2Biz.UsuarioCollection();
			
			foreach(System.Data.DataRow dr in UsuarioList )
				a.Add( new dbMantenimiento2Biz.Usuario(this, dr));
			
			// must be added afterwards
			a.DataManager = this;
	
			return a;
		}


	}
}
